version: '2.2'
# Using extensions as fragments
x-volumes:
  &mount-volumes
  - ./src/.env:/app/.env
  - ./src/plugins/asobino:/app/plugins/asobino
  - ./src/storage/logs:/app/storage/logs
  - ./src/themes/asobino:/app/themes/asobino
services:
  cms:
    image: asobino/cms
    build:
      context: .
      target: development
    ports:
      - 7000:80
    depends_on:
      - db
    volumes: *mount-volumes
    env_file: .env
  db:
    image: mysql:5.7
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: admin
    volumes:
      - ./data/mysql:/var/lib/mysql
